export const textColors = [
  {
    name: 'Black',
    hex: '#000000',
    ansi: 30,
    brightAnsi: 90,
    bgAnsi: 40,
    bgBrightAnsi: 100,
  },
  {
    name: 'Red',
    hex: '#ff0000',
    ansi: 31,
    brightAnsi: 91,
    bgAnsi: 41,
    bgBrightAnsi: 101,
  },
  {
    name: 'Green',
    hex: '#00ff00',
    ansi: 32,
    brightAnsi: 92,
    bgAnsi: 42,
    bgBrightAnsi: 102,
  },
  {
    name: 'Yellow',
    hex: '#ffff00',
    ansi: 33,
    brightAnsi: 93,
    bgAnsi: 43,
    bgBrightAnsi: 103,
  },
  {
    name: 'Blue',
    hex: '#0000ff',
    ansi: 34,
    brightAnsi: 94,
    bgAnsi: 44,
    bgBrightAnsi: 104,
  },
  {
    name: 'Magenta',
    hex: '#ff00ff',
    ansi: 35,
    brightAnsi: 95,
    bgAnsi: 45,
    bgBrightAnsi: 105,
  },
  {
    name: 'Cyan',
    hex: '#00ffff',
    ansi: 36,
    brightAnsi: 96,
    bgAnsi: 46,
    bgBrightAnsi: 106,
  },
  {
    name: 'White',
    hex: '#ffffff',
    ansi: 37,
    brightAnsi: 97,
    bgAnsi: 47,
    bgBrightAnsi: 107,
  },
  {
    name: 'Gray',
    hex: '#808080',
    ansi: 90,
    brightAnsi: 37,
    bgAnsi: 100,
    bgBrightAnsi: 47,
  },
]
